import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#353436',
        'on-error-container': '#ffdad6',
        'on-secondary': '#3c0090',
        'on-primary-container': '#4f0051',
        'on-tertiary-fixed': '#001f28',
        'inverse-surface': '#e5e2e3',
        'secondary-container': '#7000ff',
        'on-tertiary': '#003543',
        'surface-container-low': '#1c1b1c',
        'tertiary-fixed-dim': '#4cd6ff',
        background: '#131314',
        'secondary-fixed-dim': '#d1bcff',
        error: '#ffb4ab',
        'on-tertiary-fixed-variant': '#004e60',
        'on-surface': '#e5e2e3',
        'surface-bright': '#3a393a',
        'on-primary': '#5b005d',
        'on-primary-fixed-variant': '#800083',
        'on-secondary-fixed': '#23005b',
        'primary-fixed-dim': '#ffaaf6',
        'on-secondary-container': '#ddcdff',
        'on-background': '#e5e2e3',
        'surface-tint': '#ffaaf6',
        'primary-container': '#f432f6',
        'error-container': '#93000a',
        'on-primary-fixed': '#380039',
        secondary: '#d1bcff',
        'surface-container': '#201f20',
        surface: '#131314',
        'inverse-on-surface': '#313031',
        'inverse-primary': '#a800ab',
        outline: '#a2899c',
        'tertiary-container': '#009dc1',
        'primary-fixed': '#ffd7f6',
        'surface-container-highest': '#353436',
        'surface-container-high': '#2a2a2b',
        tertiary: '#4cd6ff',
        'outline-variant': '#554151',
        'on-tertiary-container': '#002e3a',
        'on-error': '#690005',
        primary: '#ffaaf6',
        'on-surface-variant': '#dabfd3',
        'surface-dim': '#131314',
        'surface-container-lowest': '#0e0e0f',
        'tertiary-fixed': '#b7eaff',
        'secondary-fixed': '#e9ddff',
        'on-secondary-fixed-variant': '#5700c9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        gutter: '24px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono'],
        'mono-data': ['JetBrains Mono'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-xl': ['Hanken Grotesk'],
        'body-sm': ['Inter'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
        'mono-data': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        glass: '0 8px 32px -8px rgba(0, 0, 0, 0.45), 0 1px 0 0 rgba(255, 255, 255, 0.04) inset',
        'glass-lg':
          '0 20px 48px -16px rgba(0, 0, 0, 0.55), 0 0 40px -20px rgba(209, 188, 255, 0.08)',
        'glass-xl':
          '0 32px 80px -16px rgba(0, 0, 0, 0.65), 0 0 60px -20px rgba(209, 188, 255, 0.12)',
        'glow-primary':
          '0 8px 28px -6px rgba(244, 50, 246, 0.45), 0 0 40px -10px rgba(255, 170, 246, 0.3)',
        'glow-sm': '0 0 24px -6px rgba(255, 170, 246, 0.25)',
        'glow-md': '0 0 40px -8px rgba(255, 170, 246, 0.35)',
      },
      transitionTimingFunction: {
        premium: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      transitionDuration: {
        premium: '200ms',
      },
      keyframes: {
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96) translateY(8px)' },
          to: { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.5s cubic-bezier(0.22, 1, 0.36, 1) both',
        'scale-in': 'scale-in 0.35s cubic-bezier(0.22, 1, 0.36, 1) both',
      },

    },
  },
  plugins: [],
} satisfies Config